# Generated by Django 2.1.5 on 2019-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_auto_20180920_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=12)),
                ('status', models.CharField(choices=[('refunded', 'refunded'), ('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=32)),
                ('ref_number', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
