# Generated by Django 2.1.5 on 2019-09-02 09:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0075_remove_suborder_subtotal'),
        ('shop', '0016_auto_20190830_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('customer_name', models.CharField(blank=True, max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('customer_name', models.CharField(blank=True, max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SuborderPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('customer_name', models.CharField(blank=True, max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='order.Order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.Shop')),
                ('suborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='order.SubOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', saleor.wallet.models.PossiblePhoneNumberField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
