# Generated by Django 2.1.5 on 2019-10-14 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsTemporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('shipping_payment_status', models.CharField(choices=[('refunded', 'refunded'), ('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=32)),
                ('order_payment_status', models.CharField(choices=[('refunded', 'refunded'), ('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=32)),
                ('ref_number_shipping', models.CharField(blank=True, max_length=100)),
                ('ref_number_order', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
