# Generated by Django 2.1.5 on 2019-10-15 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_paymentstemporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstemporary',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temppayments', to=settings.AUTH_USER_MODEL),
        ),
    ]
