# Generated by Django 2.1.5 on 2019-10-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20191015_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstemporary',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temppayments', to='order.Order'),
        ),
    ]
