# Generated by Django 2.1.5 on 2019-05-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_auto_20190122_0113'),
        ('shop', '0003_auto_20190417_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcategories', to='shop.Shop')),
                ('shop_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='product.Category')),
            ],
        ),
    ]
