# Generated by Django 2.1.5 on 2019-05-18 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategories',
            name='shop_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcategories', to='product.Category'),
        ),
    ]
