# Generated by Django 2.1.5 on 2019-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190525_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.Shop'),
        ),
    ]
