# Generated by Django 2.1.5 on 2019-08-30 14:37

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190830_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('logo', versatileimagefield.fields.VersatileImageField(upload_to='logos')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Shop')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
