# Generated by Django 2.1.5 on 2019-08-30 14:41

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
