# Generated by Django 2.1.5 on 2019-09-07 10:56

from django.db import migrations
import saleor.shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190904_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=saleor.shop.models.PossiblePhoneNumberField(blank=True, default='', max_length=128),
        ),
    ]
