# Generated by Django 2.1.5 on 2019-12-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20191014_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
