# Generated by Django 2.1.5 on 2019-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20191211_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
