# Generated by Django 2.1.5 on 2019-12-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20191211_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='logo_image',
        ),
    ]
