# Generated by Django 2.1.5 on 2019-12-11 17:03

from django.db import migrations, models
import saleor.shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_shop_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=saleor.shop.models.PossiblePhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=256),
        ),
    ]
