# Generated by Django 2.1.5 on 2019-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20181102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
