# Generated by Django 2.1.5 on 2019-07-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='suborder',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborderlines', to='order.SubOrder'),
        ),
    ]
