# Generated by Django 2.1.5 on 2019-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_remove_suborder_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='subtotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
