# Generated by Django 2.1.5 on 2019-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_remove_suborder_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'pending'), ('received', 'received')], default='pending', max_length=32),
        ),
    ]
