# Generated by Django 2.1.5 on 2019-09-07 10:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import saleor.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_suborder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=386)),
                ('customer_phone', saleor.order.models.PossiblePhoneNumberField(blank=True, default='', max_length=128)),
                ('shop_name', models.CharField(max_length=386)),
                ('shop_phone', saleor.order.models.PossiblePhoneNumberField(blank=True, default='', max_length=128)),
                ('ref_number', models.CharField(blank=True, max_length=386, validators=[django.core.validators.RegexValidator('^(A-Fa-f0-9)+$', message='Not a Valid Mpesa Reference Number')])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('status', models.CharField(choices=[('refunded', 'refunded'), ('pending', 'pending'), ('sent', 'sent')], default='pending', max_length=15)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orderpaymentout', to='order.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='suborder',
            name='order_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopsuborders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'pending'), ('received', 'delivered')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='suborder',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='suborderpaymentout', to='order.SubOrder'),
        ),
    ]
