# Generated by Django 2.1.5 on 2019-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20190907_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='order_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
