# Generated by Django 2.1.5 on 2019-10-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20190907_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order_delivery',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'pending'), ('received', 'delivered')], default='pending', max_length=32),
        ),
    ]
