# Generated by Django 2.1.5 on 2019-10-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_order_status_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='shop_location',
            field=models.CharField(blank=True, max_length=386),
        ),
    ]
