# Generated by Django 2.1.5 on 2019-10-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_orderline_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='shop',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoporderlines', to='shop.Shop'),
        ),
    ]
