# Generated by Django 2.1.5 on 2019-10-28 16:26

from django.db import migrations
import django_prices.models
import saleor.core.utils.taxes


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20191026_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='amount',
        ),
        migrations.AddField(
            model_name='suborder',
            name='amount_gross',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
        migrations.AddField(
            model_name='suborder',
            name='amount_net',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
    ]
