# Generated by Django 2.1.5 on 2019-11-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0086_auto_20191028_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='order_owner',
        ),
        migrations.AddField(
            model_name='suborder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborders', to=settings.AUTH_USER_MODEL),
        ),
    ]
