# Generated by Django 2.1.5 on 2019-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_shopimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
