# Generated by Django 2.1.5 on 2019-10-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20191014_1829'),
        ('product', '0087_auto_20190830_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_products', to='shop.Shop'),
        ),
    ]
