# Generated by Django 2.1.5 on 2019-12-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20191224_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shop.Shop'),
        ),
    ]
